// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DxBlazorIdentity.Models
{
    public partial class Video
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public DateTime VideoDate { get; set; }
        public string Source { get; set; }
        public string VideoCode { get; set; }
        public string DownloadUrl { get; set; }
        public string ThumbnailUrl { get; set; }
    }
}